[project]
name = "demo_2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8,<3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "pandas>=2.3.0",
    "pytest>=8.4.1",
]

[tool.uv]
python-downloads = "never"
python-preference = "only-system"
cache-dir = ".uv-cache"
package = false
